version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - .:/app
#    depends_on:
#      - db
    environment:
      - RAILS_ENV=development
    command: rails server -b 0.0.0.0
#  db:
#    image: postgres:latest
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=your_username
#      - POSTGRES_PASSWORD=your_password
#      - POSTGRES_DB=your_database
